/**
 * @file Agent.hpp
 * @author Daniel Ingham
 * @date 2026-06-06
 */
#pragma once

#include "CL/agent/agent.hpp"
#include "CL/common/estimation_parameters.hpp"
#include "CL/filters/ekf.hpp"
#include "CL/filters/filter.hpp"
#include "CL/sensors/measurements.hpp"
#include "CL/sensors/odometry.hpp"

#include <UtiasMrclam/DataHandler.hpp>
#include <UtiasMrclam/agents/Robot.hpp>
#include <cassert>
#include <memory>
#include <type_traits>

namespace CL {

/**
 * Mobile robot agent in the VANET. This agent attempts to localise itself
 * within the environment using a combination of its on-board sensors and the
 * shared state information of surrounding agents.
 */
class Robot : public Agent {

public:
  Robot() = delete;
  Robot(Robot &&) = default;
  Robot(const Robot &) = delete;
  Robot &operator=(Robot &&) = delete;
  Robot &operator=(const Robot &) = delete;
  ~Robot() = default;

  /**
   * Robot builder. Creates a robot with a specified filter type and Robot
   * behaviour type.
   * @param data Robot data extracted from the dataset/simulation.
   * @returns Instance of the robot class.
   */
  template <typename FilterType = CL::filter::EKF, typename RobotType = Robot>
  static std::unique_ptr<Robot> create(const utias::mrclam::Robot &data) {
    static_assert(std::is_base_of_v<filter::Filter, FilterType>,
                  "FilterType must be derived from base class filter::Filter.");

    static_assert(std::is_base_of_v<Robot, RobotType>,
                  "Type T must be derived from base class filter::Filter.");

    std::unique_ptr<Robot> robot{new RobotType{data}};

    robot->filter_ = std::make_unique<FilterType>(robot->getPrior());

    return robot;
  }

  /**
   * Uses odometry to compute the predictive density for its state, create a
   * "broadcast" its estimate over the vanet.
   * @param index The current index in the UTIAS MRCLAM synced set.
   */
  const EstimationParameters &broadcastEstimate(size_t index) override;

  /**
   * Getter for the messages (Estimates) broadcasted by other agents on the
   * VANET.
   * @param index Time index.
   * @param vanet_msgs Map containing the agent barcode (key) and estimate
   * (value).
   */
  void recieveVanetMessages(
      size_t index, std::map<unsigned short, EstimationParameters> &vanet_msgs);

  /**
   * @returns the list of the estimates produced by the agent for its entire
   * trajectory.
   */
  const std::vector<EstimationParameters> &getEstimates() const;

  /**
   * @returns the prior distribution of the systems state.
   */
  const EstimationParameters &getPrior() { return estimates_.front(); }

protected:
  /**
   * Protected constructor
   * @data data Robot data extracted from the dataset/simulation.
   */
  Robot(const utias::mrclam::Robot &data);

  /**
   * Type of filter used by the agent for state estimation.
   */
  std::unique_ptr<filter::Filter> filter_;

  /**
   * List of estimates generated by the agent during operation.
   */
  std::vector<EstimationParameters> estimates_;

  /**
   * List of odometry inputs/measurements generated by the agent's sensor.
   */
  std::unique_ptr<sensors::Odometry> odometry_;

  /**
   * List observations/measurement generated by the agent's sensor.
   */
  const std::vector<utias::mrclam::Robot::Measurement> &measurements_;

  std::unique_ptr<sensors::Measurements> new_measurements_;

  // Measurements

  /**
   * Sample period of the agents sensors.
   */
  double sample_period_;

private:
};
} // namespace CL
